### ISSUE TITLE
Unable to run "First Model Fit" from README.md

### ISSUE THREAD

**Issue by neheller** [LBHB/NEMS0#44]
```
(nems) helle246@jupiter:~/software/nems/scripts$ python fit_model.py $INPUT_URI $MODELKEYWORDS $DESTINATION
[nems.default_config INFO] Saving log messages to /tmp/nems/NEMS 2018-04-09 151227.log
[nems WARNING] No NEMS_CONFIG defined
/home/helle246/envs/nems/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[nems.xforms INFO] Evaluating: nems.xforms.load_recordings
[nems.recording INFO] got response: {'x-amz-request-id': 'D6F2FF18AAE145DF', 'Date': 'Mon, 09 Apr 2018 20:12:27 GMT', 'Transfer-Encoding': 'chunked', 'Server': 'AmazonS3', 'x-amz-id-2': 'Rzo5A+v9b92Hdx+jQ+P6bfFOM2tvWcGT7Ndzr5umJdkpSqiRPuFeBdukrxuMFnliAxWdawODrqA=', 'Content-Type': 'application/xml'}, 404
[nems.recording ERROR] Error loading URL: https://s3-us-west-2.amazonaws.com/nemspublic/sample_data/TAR010c-18-1.tar.gz
Traceback (most recent call last):
  File "fit_model.py", line 64, in <module>
    main()
  File "fit_model.py", line 60, in main
    fit_model(args.recording, args.modelkwstring, args.destination)
  File "fit_model.py", line 30, in fit_model
    ctx, log = xforms.evaluate(xfspec)
  File "/home/helle246/software/nems/nems/xforms.py", line 126, in evaluate
    context = evaluate_step(xfa, context)
  File "/home/helle246/software/nems/nems/xforms.py", line 85, in evaluate_step
    new_context = fn(**args)
  File "/home/helle246/software/nems/nems/xforms.py", line 145, in load_recordings
    rec = load_recording(recording_uri_list[0])
  File "/home/helle246/software/nems/nems/recording.py", line 737, in load_recording
    rec = load_recording_from_url(http_uri(uri))
  File "/home/helle246/software/nems/nems/recording.py", line 778, in load_recording_from_url
    raise Exception(m)
Exception: Error loading URL: https://s3-us-west-2.amazonaws.com/nemspublic/sample_data/TAR010c-18-1.tar.gz
```
Looks like the provided URL is giving a 404
```
(nems) helle246@jupiter:~/software/nems/scripts$ wget $INPUT_URI 
--2018-04-09 15:16:08--  https://s3-us-west-2.amazonaws.com/nemspublic/sample_data/TAR010c-18-1.tar.gz
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.128.144
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.128.144|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-09 15:16:08 ERROR 404: Not Found.
```

**Comment by jacobpennington** [comment]
Fixed in docs branch, file on s3 got switched from .tar.gz to .tgz at some point.
